### ISSUE TITLE
缓存自动清除

### ISSUE THREAD

**Issue by lentikr** [blllld/WeatherView#1]
能否自动删除之前的缓存？因为今日之前的天气信息说实话不会再用到了。

**Comment by blllld** [comment]
> 能否自动删除之前的缓存？因为今日之前的天气信息说实话不会再用到了。

你是不需要缓存数据吗?
如果不需要缓存天气的话,我可以增加一个配置方案拒绝缓存.不过这样的话日记当天的天气情况就没办法存在了.

**Comment by lentikr** [comment]
> 从天气站点获取当天的天气情况,并缓存下来. 下一次再打开此笔记时,可以看到笔记当天的天气情况.

原来您是这样设计的，我是想把这个插件添加到我的主页里，所以每次重新获取就好。

**Comment by blllld** [comment]
> 原来您是这样设计的，我是想把这个插件添加到我的主页里，所以每次重新获取就好。
有两种选择:

1. 配置isToday = true，这样只会显示当天的天气，但是会缓存。
2. 配置cacheable = false，这样就不会缓存天气，每次打开都会重新获取。

缓存文件按年号缓存在`.obsidian/.weather-stats-{YEAR}`下，可以直接删除，一年也存不了太多数据，不影响使用。
